feat: pass request to the queryString function
fastify/fastify-reply-from pull request #365
Opened 2024-04-19 15:25 UTC by ttshivers

Pass the request to the queryString function in the same way that rewriteRequestHeaders has access to the request object.

Fixes: #364

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-04-20 16:24 UTC, mcollina requested changes

2024-04-20 19:14 UTC, ttshivers commented on types/index.d.ts
> +  ) => string;
Added a test in a new commit. Is that what you were looking for?

2024-04-22 08:48 UTC, mcollina approved these changes
lgtm

2024-04-22 09:19 UTC, gurgunday approved these changes

2024-04-22 12:14 UTC, merged